os: linux

language: node_js

node_js:
  - 10

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  fqdn: qianguodong.xyz
  on:
    branch: master
    local_dir: public
    target_branch: gh_pages

